#The World's Most Annoying E-Book
#Created by Rich Williams

#Concepts Used:
    #print()
    #input()
    #newline
    #tab
    #comments

print("\n\t\tThe World's Most Annoying E-Book")
print("\n\n\nBy Rich Williams")
input("\nPress Enter to Begin")

#Title

print("\n\nA Tale of Two Cities")
print("By Charles Dickens")
input("\n\nPress Enter to Continue")

#The Really Annoying Part

print("\n\nIt")
print("was")
print("the")
print("best")
print("of")
print("times,")
print("it")
print("was")
print("the")
print("worst")
print("of")
print("times,")
print("it")
print("was")
print("the")
print("age")
print("of")
print("wisdom,")
print("it")
print("was")
print("the")
print("age")
print("of")
print("foolishness,")
print("it")
print("was")
print("the")
print("epoch")
print("of")
print("belief,")
print("it")
print("was")
print("the")
print("epoch")
print("of")
print("incredulity,")
print("it")
print("was")
print("the")
print("season")
print("of")
print("Light,")
print("it")
print("was")
print("the")
print("season")
print("of")
print("Darkness,")
print("it")
print("was")
print("the")
print("spring")
print("of")
print("hope,")
print("it")
print("was")
print("the")
print("winter")
print("of")
print("despair,")
print("we")
print("had")
print("everything")
print("before")
print("us,")
print("we")
print("had")
print("nothing")
print("before")
print("us,")
print("we")
print("were")
print("all")
print("going")
print("direct")
print("to")
print("heaven,")
print("we")
print("were")
print("all")
print("going")
print("direct")
print("the")
print("other")
print("way")
print("-")
print("in")
print("short")
print("the")
print("period")
print("was")
print("so")
print("far")
print("like")
print("the")
print("present")
print("period,")
print("that")
print("some")
print("of")
print("its")
print("noisiest")
print("authorities")
print("insisted")
print("on")
print("its")
print("being")
print("received,")
print("for")
print("good")
print("or")
print("for")
print("evil,")
print("in")
print("the")
print("superlative")
print("degree")
print("of")
print("comparison")
print("only.")

#Conclusion

input("\nDo you really want to continue?")

print("\nThen go buy a Kindle")
input("\n\nPress Enter to Exit")
